services:
  web:
    build: .
    ports:
      - "5001:8000" # Voltamos para a porta 5001, como o Nginx espera
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    restart: unless-stopped
    networks:
      - pbpm_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - pbpm_network

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - pbpm_network

volumes:
  postgres_data:
  ollama_data:

networks:
  pbpm_network:
    driver: bridge