name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar conexão SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

    - name: Deploy na VPS
      run: |
        ssh-keyscan -H ${{ secrets.VPS_SSH_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.VPS_SSH_USERNAME }}@${{ secrets.VPS_SSH_HOST }} << 'EOF'
          cd ~/pbpm || git clone https://github.com/${{ github.repository }}.git ~/pbpm
          cd ~/pbpm
          git pull
          echo "${{ secrets.DOT_ENV }}" > .env
          
          # Comando correto: Para, recria e sobe os containers com as novas configurações.
          docker compose up --build --force-recreate -d

        EOF